# Configuration example
rsrc:
  directories:
    images: # exemplar of directory
      path: # path to directory
      type: # type of files, which contains in directory
      access: # access handler, it will be class
      cache: # cache rule for directory
        size: # cache size
        warmingUp: # true/false - is cache will be warming up on application startup
    videos:
      path:
      type:
      access:
      cache: